---
title: "Geographica"
author: "Qi Yuchen (yq2279)"
date: "2019/11/27"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(plotly)
library(readxl)
library(countrycode)
library(flexdashboard)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 12, 
  fig.asp = .618,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Data cleaning

```{r}
## add continents
df = read_xls("data/Chapter2OnlineData.xls") %>% 
  janitor::clean_names()
df = df %>% 
  mutate(continent = countrycode(sourcevar = country_name,
                                 origin = "country.name",
                                 destination = "continent")) %>% 
  select(continent, country_name, everything())
## Some values were not matched unambiguously: Kosovo
```

## Geographica

```{r}
df_geo = df %>% 
  select(continent, country = country_name, year, life_ladder) %>% 
  group_by(continent, country) %>% 
  summarise(mean_life_ladder = mean(life_ladder)) %>% 
  filter(country != "Kosovo") %>% 
  ungroup()




```

### Distribution of happiness in each continent

```{r}
# Africa
df_geo %>% 
  filter(continent == "Africa") %>% 
  mutate(country = reorder(country, mean_life_ladder)) %>% 
  plot_ly(x = ~country, y = ~mean_life_ladder, color = ~country, type = "bar") %>% 
  layout(
    title = "Distribution of happiness in Africa",
    xaxis = list(title = "country name", tickangle = -45),
    yaxis = list(title = "expectation of life ladder")
    )
```

```{r}
# Americas
df_geo %>% 
  filter(continent == "Americas") %>% 
  mutate(country = reorder(country, mean_life_ladder)) %>% 
  plot_ly(x = ~country, y = ~mean_life_ladder, color = ~country, type = "bar") %>% 
  layout(
    title = "Distribution of happiness in Americas",
    xaxis = list(title = "country name", tickangle = -45),
    yaxis = list(title = "expectation of life ladder")
    )
```

```{r}
# Asia & Oceania
df_geo %>% 
  filter(continent == "Asia" | continent == "Oceania") %>% 
  mutate(country = reorder(country, mean_life_ladder)) %>% 
  plot_ly(x = ~country, y = ~mean_life_ladder, color = ~country, type = "bar") %>% 
  layout(
    title = "Distribution of happiness in Asia",
    xaxis = list(title = "country name", tickangle = -45),
    yaxis = list(title = "expectation of life ladder")
    )
```

```{r}
# Europe
df_geo %>% 
  filter(continent == "Europe") %>% 
  mutate(country = reorder(country, mean_life_ladder)) %>% 
  plot_ly(x = ~country, y = ~mean_life_ladder, color = ~country, type = "bar") %>% 
  layout(
    title = "Distribution of happiness in Europe",
    xaxis = list(title = "country name", tickangle = -45),
    yaxis = list(title = "expectation of life ladder")
    )
```

