---
title: "Final Project Proposal"
date: "November 7, 2018"
output: github_document
---


## Members (names and UNIs)
* Shuya Liu(sl4655)
* Yuchen Qi(yq2279)
* Xiaoyang Li(xl2934)
* Di Wu(dw2903)
* Jingyu Fu(jf3286)

## Topic

Happiness

## Motivation and Intended Final Products

In living memory, people paid a lot of attention to their health, especially their physical health. Yet with the development of modern technology in medicine and a more comprehensive medical care system, the general physical health of the majority seems to be in good care. With the guarantee of their basic physical health, people tend to pay more attention to their mental health. This tendency drives the more frequent appearance of depressing topics such as “Depression” and “Suicide”. Yet, in order to make progress and actually change the depressing situation, people should not only focus on these issues, but also concentrate on happier thoughts. Hence, in this research, we focus on happiness, how people feel about their well-being and happiness across countries, and focus on how the feeling of happy changes over years and the association or even casual effects between several variables and happiness in the United States.  

## Data Source

This research introduces several datasets in order for a comprehensive analysis:  

* Index related to happiness is from the release of the Gallup World Poll.  
https://www.gallup.com/analytics/214565/universities-colleges-using-gallup-analytics.aspx  

* GDP per capita in purchasing power parity (PPP) at constant 2011 international dollar prices are from the World Development Indicators (WDI).  
https://datacatalog.worldbank.org/dataset/world-development-indicators  

* Healthy life expectancies at birth are based on the data extracted from the World Health Organization’s (WHO) Global Health Observatory data repository  
https://www.who.int/gho/database/en/  

## Planned analyses / visualizations / coding challenges
* How happiness is changed through the years and the distribution of levels of happiness in different areas changed.
* How the rise of TV, Internet and smartphone technology affect our happiness?
Intend to analyze the association between screen time spent on electronic devices and happiness.
* Happiness and prosocial behavior: intend to analyze the association between generosity and happiness and compare the association in different regions shown with a map.
* How happiness is related to the living environment, dining, income, education, health status and any possible factors its certain area. 

## Planned timeline

|Deadline	 | Description          | Date        | Assignment                 
|----------|----------------------|-------------|----------------------------
|Nov. 7	   |Proposal	             |Nov.1-Nov.7	 |Data and Proposal           
|Nov.11-15 |Project Review Meeting |Nov.7-Nov.11 |	Data and repo homepage     
|Dec.5	   |Report	               |Nov.11-16    |	Data Cleansing and Grouping
|          |    		               |Nov.18-23	   |1st Draft and Group Meet    
|          |    		               |Nov.25-30	   |2nd Draft and Group Meet  
|          |    		               |Dec.1-5	     |Final Details and Report    
